name: image_circular_progress
description: "Image Circular Progress"
version: 1.0.0
homepage: https://github.com/andersonmatte/image_circular_progress
repository: https://github.com/andersonmatte/image_circular_progress
issue_tracker: https://github.com/andersonmatte/image_circular_progress/issues
documentation: https://github.com/andersonmatte/image_circular_progress#readme

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.24.0

flutter:
  assets:
    - assets/
